[package]
name = "oscquery"
version = "0.1.0"
authors = ["Alex Norman <xnor@perfectco.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.5.0"
